export enum ElementType{
    Normal = 'NORMAL',
    Fighting = 'FIGHTING',
    Flying = 'FLYING',
    Poison = 'POISON',
    Ground = 'GROUND',
    Rock ='ROCK',
    Bug ='BUG',
    Ghost ='GHOST',
    Steel ='STEEL',
    Fire ='FIRE',
    Water ='WATER',
    Grass = 'GRASS',
    Electric ='ELECTRIC',
    Psychic ='PSYCHIC',
    Ice ='ICE',
    Dragon = 'DRAGON',
    Dark ='DARK',
    Fairy ='FAIRY',
    None = 'NONE'
}